services:
  app:
    env_file: .env
    build:
      context: ../
      dockerfile: ./docker/Dockerfile
    container_name: ${SERVICE_NAME}
    working_dir: /src/app
    volumes:
      - ../app:/src/app
    ports:
      - ${PUBLIC_HTTP_PORT}:${PRIVATE_HTTP_PORT}
    stdin_open: true
    tty: true
    # command: python -B app.py
    environment:
      FLASK_DEBUG: 1
      FLASK_APP: ./app.py
      PYTHONPYCACHEPREFIX: $HOME/.cache/cpython/
    entrypoint:
      - flask
      - run
      - --host=0.0.0.0
      - --debug=True
      - --load_dotenv=True