services:
  app:
    env_file: .env
    build:
      context: ../
      dockerfile: ./docker/Dockerfile
    container_name: ${SERVICE_NAME}
    working_dir: /src/app
    volumes:
      - ../app:/src/app
    ports:
      - ${PUBLIC_HTTP_PORT}:${PRIVATE_HTTP_PORT}
    stdin_open: true
    tty: true
    # command: python -B app.py
    environment:
      FLASK_DEBUG: 1
      FLASK_APP: ./app.py
      PYTHONPYCACHEPREFIX: $HOME/.cache/cpython/
    entrypoint:
      - flask
      - run
      - --host=0.0.0.0
      - --debug
  db:
    env_file: .env
    image: postgres:17.5
    container_name: ${SERVICE_NAME}_db
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: 3PL
    ports:
      -  ${POSTGRES_PUBLIC_PORT}:${POSTGRES_PRIVATE_PORT}
volumes:
  postgres_data: