"""fix field name

Revision ID: 1604fdd9edf7
Revises: 5e00c1eddbf3
Create Date: 2025-06-30 11:06:29.896503

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '1604fdd9edf7'
down_revision = '5e00c1eddbf3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('status', schema=None) as batch_op:
        batch_op.add_column(sa.Column('short_description', sa.String(length=100), nullable=False))
        batch_op.drop_column('shor_description')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('status', schema=None) as batch_op:
        batch_op.add_column(sa.Column('shor_description', mysql.VARCHAR(length=100), nullable=False))
        batch_op.drop_column('short_description')

    # ### end Alembic commands ###
