"""Coutries to Currencies

Revision ID: 211692d69853
Revises: 15d159d2bd7b
Create Date: 2025-07-17 11:45:13.239422

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '211692d69853'
down_revision = '15d159d2bd7b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('countries_to_currencies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('country', sa.String(length=3), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('country')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('countries_to_currencies')
    # ### end Alembic commands ###
