"""Status

Revision ID: 5e00c1eddbf3
Revises: 2dea2aac9a79
Create Date: 2025-06-27 11:26:06.464879

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5e00c1eddbf3'
down_revision = '2dea2aac9a79'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('status',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('description', sa.String(length=250), nullable=False),
    sa.Column('shor_description', sa.String(length=100), nullable=False),
    sa.Column('status_group_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['status_group_id'], ['status_groups.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('status')
    # ### end Alembic commands ###
