"""add relationship table

Revision ID: 73479410820b
Revises: 1604fdd9edf7
Create Date: 2025-06-30 11:33:47.337726

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '73479410820b'
down_revision = '1604fdd9edf7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('status_groups_to_status',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('status_group_id', sa.Integer(), nullable=False),
    sa.Column('status_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['status_group_id'], ['status_groups.id'], ),
    sa.ForeignKeyConstraint(['status_id'], ['status.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('status_groups_to_status')
    # ### end Alembic commands ###
